import { textSummary } from 'https://jslib.k6.io/k6-summary/0.0.1/index.js';

export const BASE_URL = __ENV.BASE_URL || 'https://jsonplaceholder.typicode.com';

export function summaryHandler(testName) {
  return function handleSummary(data) {
    return {
      stdout: textSummary(data, { indent: ' ', enableColors: true }),
      [`results/${testName}.json`]: JSON.stringify(data, null, 2),
    };
  };
}

export const JSON_HEADERS = { 'Content-Type': 'application/json' };

export function randomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export function randomPostId() {
  return randomInt(1, 100);
}

export function randomUserId() {
  return randomInt(1, 10);
}

export function postPayload() {
  return JSON.stringify({
    title: `Performance test post ${randomInt(1, 1000)}`,
    body: 'Generated by k6 load test',
    userId: randomUserId(),
  });
}

export function putPayload(id) {
  return JSON.stringify({
    id,
    title: `Updated post ${id}`,
    body: 'Updated via k6 stress test',
    userId: randomUserId(),
  });
}
